INSERT INTO application_region (region_id, name, department, sub_prefecture) VALUES
(1, 'Haut-Sassandra', 'Aucun', 'Aucun'),
(11, 'Haut-Sassandra', 'Daloa', 'Aucun'),
(111, 'Haut-Sassandra', 'Daloa', 'Bédiala'),
(112, 'Haut-Sassandra', 'Daloa', 'Daloa'),
(113, 'Haut-Sassandra', 'Daloa', 'Gadouan'),
(114, 'Haut-Sassandra', 'Daloa', 'Gboguhé'),
(115, 'Haut-Sassandra', 'Daloa', 'Gonaté'),
(116, 'Haut-Sassandra', 'Daloa', 'Zaibo'),
(12, 'Haut-Sassandra', 'Issia', 'Aucun'),
(121, 'Haut-Sassandra', 'Issia', 'Boguédia'),
(122, 'Haut-Sassandra', 'Issia', 'Iboguhé'),
(123, 'Haut-Sassandra', 'Issia', 'Issia'),
(124, 'Haut-Sassandra', 'Issia', 'Nahio'),
(125, 'Haut-Sassandra', 'Issia', 'Namané'),
(126, 'Haut-Sassandra', 'Issia', 'Saïoua'),
(127, 'Haut-Sassandra', 'Issia', 'Tapéguia'),
(13, 'Haut-Sassandra', 'Vavoua', 'Aucun'),
(131, 'Haut-Sassandra', 'Vavoua', 'Bazra-Nattis '),
(132, 'Haut-Sassandra', 'Vavoua', 'Dananon '),
(133, 'Haut-Sassandra', 'Vavoua', 'Dania '),
(134, 'Haut-Sassandra', 'Vavoua', 'Kétro-Bassam'),
(135, 'Haut-Sassandra', 'Vavoua', 'Seitifla '),
(136, 'Haut-Sassandra', 'Vavoua', 'Vavoua '),
(14, 'Haut-Sassandra', 'Zoukougbeu', 'Aucun'),
(141, 'Haut-Sassandra', 'Zoukougbeu', 'Domangbeu '),
(142, 'Haut-Sassandra', 'Zoukougbeu', 'Grégbeu '),
(143, 'Haut-Sassandra', 'Zoukougbeu', 'Guessabo '),
(144, 'Haut-Sassandra', 'Zoukougbeu', 'Zoukougbeu '),
(2, 'Marahoué', 'Aucun', 'Aucun'),
(21, 'Marahoué', 'Bonon', 'Aucun'),
(211, 'Marahoué', 'Bonon', 'Bonon'),
(212, 'Marahoué', 'Bonon', 'Zaguieta'),
(22, 'Marahoué', 'Bouaflé', 'Aucun'),
(221, 'Marahoué', 'Bouaflé', 'Begbessou'),
(222, 'Marahoué', 'Bouaflé', 'Bouaflé'),
(223, 'Marahoué', 'Bouaflé', 'N''douffoukankro'),
(224, 'Marahoué', 'Bouaflé', 'Pakouabo'),
(225, 'Marahoué', 'Bouaflé', 'Tibeita'),
(23, 'Marahoué', 'Gohitafla', 'Aucun'),
(231, 'Marahoué', 'Gohitafla', 'Gohitafla'),
(232, 'Marahoué', 'Gohitafla', 'Iriéfla'),
(233, 'Marahoué', 'Gohitafla', 'Maminigui'),
(24, 'Marahoué', 'Sinfra', 'Aucun'),
(241, 'Marahoué', 'Sinfra', 'Bazré'),
(242, 'Marahoué', 'Sinfra', 'Kononfla'),
(243, 'Marahoué', 'Sinfra', 'Kouetinfla'),
(244, 'Marahoué', 'Sinfra', 'Sinfra'),
(25, 'Marahoué', 'Zuénoula', 'Aucun'),
(251, 'Marahoué', 'Zuénoula', 'Kanzra'),
(252, 'Marahoué', 'Zuénoula', 'Vouéboufla'),
(253, 'Marahoué', 'Zuénoula', 'Zanzra'),
(254, 'Marahoué', 'Zuénoula', 'Zuénoula');